import { useState, useMemo } from "react";
import { useParams } from "react-router-dom";
import _ from "lodash";
import "./PlayerStatsTabs.css";
import { useTranslation } from "react-i18next";


export const competitionStats = {
  modric: {
     "La Liga": {
    matchesPlayed: 388,
    matchesAsStarter: 306,
    matchesAsSub: 82,
    headedGoals: 0,
    rightFootedGoals: 30,
    leftFootedGoals: 0,
    penaltiesTaken: 0,
    freeKickGoals: 0,
    assists: 58,
    minutesPlayed: 26884,
    passes: 21000,
    penaltiesScored: 0,
    shots: 250,
    foulsReceived: 400,
    foulsCommitted: 350,
    ballsWonBack: 1200,
  },
  "Champions League": {
    matchesPlayed: 146,
    matchesAsStarter: 120,
    matchesAsSub: 26,
    headedGoals: 0,
    rightFootedGoals: 0,
    leftFootedGoals: 0,
    penaltiesTaken: 0,
    freeKickGoals: 0,
    assists: 20,
    minutesPlayed: 9000,
    passes: 8200,
    penaltiesScored: 0,
    shots: 80,
    foulsReceived: 120,
    foulsCommitted: 90,
    ballsWonBack: 400,
  },
  "Copa Del Rey": {
    matchesPlayed: 39,
    matchesAsStarter: 31,
    matchesAsSub: 8,
    headedGoals: 0,
    rightFootedGoals: 0,
    leftFootedGoals: 0,
    penaltiesTaken: 0,
    freeKickGoals: 0,
    assists: 6,
    minutesPlayed: 2200,
    passes: 2100,
    penaltiesScored: 0,
    shots: 30,
    foulsReceived: 40,
    foulsCommitted: 35,
    ballsWonBack: 130,
  },
   "Supercopa de Espana": {
    matchesPlayed: 10,
    matchesAsStarter: 8,
    matchesAsSub: 2,
    headedGoals: 0,
    rightFootedGoals: 1,
    leftFootedGoals: 0,
    penaltiesTaken: 0,
    freeKickGoals: 0,
    assists: 2,
    minutesPlayed: 780,
    passes: 690,
    penaltiesScored: 0,
    shots: 10,
    foulsReceived: 12,
    foulsCommitted: 8,
    ballsWonBack: 40,
  },
  "Supercopa de Europa": {
    matchesPlayed: 5,
    matchesAsStarter: 4,
    matchesAsSub: 1,
    headedGoals: 0,
    rightFootedGoals: 0,
    leftFootedGoals: 0,
    penaltiesTaken: 0,
    freeKickGoals: 0,
    assists: 1,
    minutesPlayed: 390,
    passes: 320,
    penaltiesScored: 0,
    shots: 4,
    foulsReceived: 3,
    foulsCommitted: 2,
    ballsWonBack: 15,
  },
  "FIFA Club World Cup": {
    matchesPlayed: 7,
    matchesAsStarter: 6,
    matchesAsSub: 1,
    headedGoals: 1,
    rightFootedGoals: 1,
    leftFootedGoals: 0,
    penaltiesTaken: 0,
    freeKickGoals: 0,
    assists: 2,
    minutesPlayed: 600,
    passes: 580,
    penaltiesScored: 0,
    shots: 7,
    foulsReceived: 5,
    foulsCommitted: 6,
    ballsWonBack: 20,
  },
  "Premier League": {
    matchesPlayed: 127,
    matchesAsStarter: 110,
    matchesAsSub: 17,
    headedGoals: 1,
    rightFootedGoals: 11,
    leftFootedGoals: 2,
    penaltiesTaken: 0,
    freeKickGoals: 1,
    assists: 20,
    minutesPlayed: 9500,
    passes: 8800,
    penaltiesScored: 0,
    shots: 120,
    foulsReceived: 160,
    foulsCommitted: 100,
    ballsWonBack: 500,
  },
  "Copa Intercontinental": {
    matchesPlayed: 4,
    matchesAsStarter: 3,
    matchesAsSub: 1,
    headedGoals: 0,
    rightFootedGoals: 0,
    leftFootedGoals: 0,
    penaltiesTaken: 0,
    freeKickGoals: 0,
    assists: 0,
    minutesPlayed: 320,
    passes: 0,  
    penaltiesScored: 0,
    shots: 0,  
    foulsReceived: 0, 
    foulsCommitted: 0, 
    ballsWonBack: 0, 
  },
  "World Cup": {
    matchesPlayed: 18,
    matchesAsStarter: 17,
    matchesAsSub: 1,
    headedGoals: 0,
    rightFootedGoals: 2,
    leftFootedGoals: 1,
    penaltiesTaken: 3,
    freeKickGoals: 0,
    assists: 3,
    minutesPlayed: 1600,
    passes: 1500,
    penaltiesScored: 3,
    shots: 25,
    foulsReceived: 35,
    foulsCommitted: 30,
    ballsWonBack: 110,
  },
  "EURO": {
    matchesPlayed: 12,
    matchesAsStarter: 11,
    matchesAsSub: 1,
    headedGoals: 0,
    rightFootedGoals: 2,
    leftFootedGoals: 0,
    penaltiesTaken: 1,
    freeKickGoals: 0,
    assists: 2,
    minutesPlayed: 1050,
    passes: 980,
    penaltiesScored: 1,
    shots: 14,
    foulsReceived: 20,
    foulsCommitted: 15,
    ballsWonBack: 70,
  }
},
ronaldo: {
  "La Liga": {
    matchesPlayed: 292,
    matchesAsStarter: 290,
    matchesAsSub: 2,
    headedGoals: 55,
    rightFootedGoals: 210,
    leftFootedGoals: 25,
    penaltiesTaken: 61,
    freeKickGoals: 33,
    assists: 95,
    minutesPlayed: 25_000,
    passes: 12_000,
    penaltiesScored: 61,
    shots: 1_100,
    foulsReceived: 400,
    foulsCommitted: 150,
    ballsWonBack: 300,
  },
  "Champions League": {
    matchesPlayed: 183,
    matchesAsStarter: 180,
    matchesAsSub: 3,
    headedGoals: 25,
    rightFootedGoals: 100,
    leftFootedGoals: 15,
    penaltiesTaken: 20,
    freeKickGoals: 12,
    assists: 42,
    minutesPlayed: 16_000,
    passes: 8_500,
    penaltiesScored: 20,
    shots: 600,
    foulsReceived: 200,
    foulsCommitted: 100,
    ballsWonBack: 150,
  },
  "Premier League": {
    matchesPlayed: 236,
    matchesAsStarter: 230,
    matchesAsSub: 6,
    headedGoals: 20,
    rightFootedGoals: 80,
    leftFootedGoals: 15,
    penaltiesTaken: 15,
    freeKickGoals: 10,
    assists: 50,
    minutesPlayed: 20_000,
    passes: 10_000,
    penaltiesScored: 15,
    shots: 900,
    foulsReceived: 300,
    foulsCommitted: 120,
    ballsWonBack: 250,
  },
  "Serie A": {
    matchesPlayed: 98,
    matchesAsStarter: 95,
    matchesAsSub: 3,
    headedGoals: 10,
    rightFootedGoals: 50,
    leftFootedGoals: 8,
    penaltiesTaken: 20,
    freeKickGoals: 5,
    assists: 20,
    minutesPlayed: 8_000,
    passes: 4_500,
    penaltiesScored: 20,
    shots: 400,
    foulsReceived: 150,
    foulsCommitted: 80,
    ballsWonBack: 100,
  },
  "Saudi Pro League": {
    matchesPlayed: 50,
    matchesAsStarter: 50,
    matchesAsSub: 0,
    headedGoals: 10,
    rightFootedGoals: 30,
    leftFootedGoals: 5,
    penaltiesTaken: 10,
    freeKickGoals: 5,
    assists: 10,
    minutesPlayed: 4_500,
    passes: 2_500,
    penaltiesScored: 10,
    shots: 200,
    foulsReceived: 100,
    foulsCommitted: 50,
    ballsWonBack: 50,
  },
  "World Cup": {
    matchesPlayed: 22,
    matchesAsStarter: 20,
    matchesAsSub: 2,
    headedGoals: 2,
    rightFootedGoals: 4,
    leftFootedGoals: 2,
    penaltiesTaken: 3,
    freeKickGoals: 1,
    assists: 3,
    minutesPlayed: 2_000,
    passes: 1_000,
    penaltiesScored: 3,
    shots: 80,
    foulsReceived: 50,
    foulsCommitted: 30,
    ballsWonBack: 60,
  },
  "EURO": {
    matchesPlayed: 30,
    matchesAsStarter: 28,
    matchesAsSub: 2,
    headedGoals: 5,
    rightFootedGoals: 6,
    leftFootedGoals: 3,
    penaltiesTaken: 5,
    freeKickGoals: 2,
    assists: 6,
    minutesPlayed: 2_700,
    passes: 1_500,
    penaltiesScored: 5,
    shots: 100,
    foulsReceived: 60,
    foulsCommitted: 25,
    ballsWonBack: 70,
  },
  "UEFA Nations League": {
    matchesPlayed: 18,
    matchesAsStarter: 16,
    matchesAsSub: 2,
    headedGoals: 3,
    rightFootedGoals: 7,
    leftFootedGoals: 3,
    penaltiesTaken: 2,
    freeKickGoals: 1,
    assists: 2,
    minutesPlayed: 1_500,
    passes: 800,
    penaltiesScored: 2,
    shots: 50,
    foulsReceived: 30,
    foulsCommitted: 15,
    ballsWonBack: 40,
  },
  "Arab Club Champions Cup": {
    matchesPlayed: 6,
    matchesAsStarter: 6,
    matchesAsSub: 0,
    headedGoals: 2,
    rightFootedGoals: 3,
    leftFootedGoals: 1,
    penaltiesTaken: 1,
    freeKickGoals: 0,
    assists: 1,
    minutesPlayed: 540,
    passes: 300,
    penaltiesScored: 1,
    shots: 20,
    foulsReceived: 10,
    foulsCommitted: 5,
    ballsWonBack: 10,
  },
  "FIFA Club World Cup": {
    matchesPlayed: 8,
    matchesAsStarter: 8,
    matchesAsSub: 0,
    headedGoals: 1,
    rightFootedGoals: 3,
    leftFootedGoals: 1,
    penaltiesTaken: 1,
    freeKickGoals: 1,
    assists: 2,
    minutesPlayed: 720,
    passes: 400,
    penaltiesScored: 1,
    shots: 30,
    foulsReceived: 15,
    foulsCommitted: 10,
    ballsWonBack: 20,
  }
},
kaka: {
    "Serie A": {
      matchesPlayed: 193,
      matchesAsStarter: 180,
      matchesAsSub: 13,
      headedGoals: 7,
      rightFootedGoals: 54,
      leftFootedGoals: 4,
      penaltiesTaken: 13,
      freeKickGoals: 5,
      assists: 43,
      minutesPlayed: 15400,
      passes: 13000,
      penaltiesScored: 12,
      shots: 380,
      foulsReceived: 310,
      foulsCommitted: 90,
      ballsWonBack: 300,
    },
    "La Liga": {
      matchesPlayed: 85,
      matchesAsStarter: 67,
      matchesAsSub: 18,
      headedGoals: 2,
      rightFootedGoals: 19,
      leftFootedGoals: 1,
      penaltiesTaken: 3,
      freeKickGoals: 2,
      assists: 15,
      minutesPlayed: 5600,
      passes: 4700,
      penaltiesScored: 3,
      shots: 150,
      foulsReceived: 100,
      foulsCommitted: 50,
      ballsWonBack: 120,
    },
    "Champions League": {
      matchesPlayed: 86,
      matchesAsStarter: 75,
      matchesAsSub: 11,
      headedGoals: 3,
      rightFootedGoals: 18,
      leftFootedGoals: 2,
      penaltiesTaken: 5,
      freeKickGoals: 3,
      assists: 25,
      minutesPlayed: 7200,
      passes: 6000,
      penaltiesScored: 5,
      shots: 140,
      foulsReceived: 90,
      foulsCommitted: 40,
      ballsWonBack: 200,
    },
    "FIFA Club World Cup": {
      matchesPlayed: 3,
      matchesAsStarter: 3,
      matchesAsSub: 0,
      headedGoals: 1,
      rightFootedGoals: 1,
      leftFootedGoals: 0,
      penaltiesTaken: 0,
      freeKickGoals: 0,
      assists: 2,
      minutesPlayed: 270,
      passes: 230,
      penaltiesScored: 0,
      shots: 10,
      foulsReceived: 8,
      foulsCommitted: 4,
      ballsWonBack: 30,
    },
    "World Cup": {
      matchesPlayed: 10,
      matchesAsStarter: 9,
      matchesAsSub: 1,
      headedGoals: 1,
      rightFootedGoals: 2,
      leftFootedGoals: 0,
      penaltiesTaken: 0,
      freeKickGoals: 0,
      assists: 4,
      minutesPlayed: 720,
      passes: 680,
      penaltiesScored: 0,
      shots: 20,
      foulsReceived: 15,
      foulsCommitted: 10,
      ballsWonBack: 50,
    }
  }
};


export default function PlayerStatsTabs() {
  const { playerId } = useParams();
  const { t } = useTranslation();

  const playerStats = competitionStats[playerId];

  const defaultTab = useMemo(() => {
    return playerStats ? Object.keys(playerStats)[0] : null;
  }, [playerStats]);

  const [selectedTab, setSelectedTab] = useState(defaultTab);

  if (!playerStats) {
    return <div>No stats available for this player.</div>;
  }

  const stats = playerStats[selectedTab];

  return (
    <div className="player-stats-tabs">
      <div className="tab-buttons">
        {Object.keys(playerStats).map((competition) => (
          <button
            key={competition}
            className={selectedTab === competition ? "active" : ""}
            onClick={() => setSelectedTab(competition)}
          >
            {t(competition)}
          </button>
        ))}
      </div>

      <div className="tab-content">
        {_.map(stats, (value, key) => (
          <div key={key} className="stat-row">
            <span className="stat-label">{t(_.startCase(key))}</span>
            <span className="stat-value">{value}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
